def get_calls(foo=None):
    calls = list()
    calls.append(['addEventListener', ['constant', 'this', 'string']])
    calls.append(['System.currentTimeMillis', list()])
    calls.append(['update', ['tick']])
    calls.append(['sendBallUpdate', list()])
    calls.append(['Thread.sleep', ['interval']])
    calls.append(['synchronized', list()])
    calls.append(['updatePaddle', ['paddle', 'tick']])
    calls.append(['updateBall', list()])
    calls.append(['paddle.setY', ['new_y']])
    calls.append(['ball.getx', list()])
    calls.append(['ball.gety', list()])
    calls.append(['ball.setx', ['x']])
    calls.append(['ball.sety', ['y']])
    calls.append(['bounceBall', ['value']])
    calls.append(['ball.setSpeed', ['speed']])
    calls.append(['sendScoreUpdate', list()])
    calls.append(['resetBall', list()])
    calls.append(['sendBallUpdate', list()])
    calls.append(['ball.setDirection', ['dir']])
    calls.append(['math.random', list()])
    calls.append(['ctx.getRoom', list()])
    calls.append(['.setAttribute', ['score', 'leftScore', 'SCOPE', 'FLAG']])
    calls.append(['evt.getClient', list()])
    calls.append(['sendMessage', ['START_GAME']])
    calls.append(['notify', list()])
    calls.append(['removeEventlistener', ['const', 'this', 'onClientChanged']])
    calls.append(['evt.getAttribute', list()])
    calls.append(['getScope', list()])
    calls.append(['equals', ['stuff']])
    calls.append(['getQualifiedID', list()])
    calls.append(['nullSafeGetValue', list()])
    calls.append(['.split', ['param']])
    

    return calls
    
if __name__ == '__main__':
    print get_calls()
